const beaches = [
  {key:'gwangalli', score:92, temp:'23℃', users:18, waiting:27, icon:'😊', water:'safe', weather:'sunny', waves:'low'},
  {key:'haeundae', score:88, temp:'22℃', users:26, waiting:34, icon:'🙂', water:'safe', weather:'cloudy', waves:'medium'},
  {key:'songjeong', score:84, temp:'22℃', users:12, waiting:16, icon:'🙂', water:'safe', weather:'overcast', waves:'medium'},
  {key:'dadaepo', score:79, temp:'21℃', users:10, waiting:8, icon:'😐', water:'caution', weather:'windy', waves:'high'},
  {key:'songdo', score:90, temp:'23℃', users:15, waiting:19, icon:'😊', water:'safe', weather:'sunny', waves:'low'}
];
const translations = {
  ko:{eyebrow:'BEACH SAFETY GUIDE',title:'안전한 바다 여행의 시작',subtitle:'오늘의 바다 상태를 확인하고, 더 가볍게 떠나세요.',search:'해수욕장 검색',water:'수질 상태',weather:'날씨',temperature:'수온',waves:'파도',facility:'BEACH FACILITY',showerTitle:'샤워실 대기 현황',live:'실시간',using:'현재 이용자',waiting:'대기자',waitTime:'예상 대기',join:'대기 등록하기',note:'안전 정보는 참고용입니다. 현장 안내 및 안전요원의 지시를 우선해 주세요.',reservation:'SHOWER RESERVATION',formTitle:'샤워 대기 등록',party:'이용 인원',phone:'연락처',consent:'개인정보 이용에 동의합니다.',register:'등록하기',updated:'방금 업데이트됨',queue:'현재 {n}명이 샤워실을 기다리고 있어요.',form:'{beach} 샤워실 대기줄에 등록합니다.',registered:'대기 등록이 완료됐어요! 순서가 가까워지면 알려드릴게요.',safe:'🟢 안전',caution:'🟡 주의',sunny:'맑음 ☀️',cloudy:'구름 조금 ⛅',overcast:'구름 많음 ☁️',windy:'바람 강함 💨',low:'낮음',medium:'보통',high:'높음',minute:'분',room:'샤워실 선택',male:'남자 샤워실',female:'여자 샤워실',enter:'입장 확인',exit:'퇴장 확인',availableAt:'예상 이용 가능 시각',availableNow:'지금 바로 이용 가능',myTime:'내 예상 이용 시각',myTurn:'샤워실 이용 순서입니다. 입장을 확인해 주세요.',inUse:'샤워실 이용 중입니다.',exited:'샤워실 퇴장이 확인됐어요.',entryDone:'입장이 확인됐습니다. 즐겁고 안전하게 이용해 주세요!',exitDone:'퇴장이 확인됐습니다. 이용해 주셔서 감사합니다!'},
  en:{eyebrow:'BEACH SAFETY GUIDE',title:'Start a safer beach day',subtitle:'Check the sea conditions and head out lighter.',search:'Search a beach',water:'Water quality',weather:'Weather',temperature:'Water temp.',waves:'Waves',facility:'BEACH FACILITY',showerTitle:'Shower queue',live:'LIVE',using:'Using now',waiting:'In queue',waitTime:'Est. wait',join:'Join the queue',note:'Safety data is for reference. Always follow local notices and lifeguards.',reservation:'SHOWER RESERVATION',formTitle:'Join shower queue',party:'Party size',phone:'Phone number',consent:'I agree to use of my personal information.',register:'Register',updated:'Updated just now',queue:'{n} people are currently waiting.',form:'Join the queue for {beach}.',registered:'You are in the queue! We will notify you when it is almost your turn.',safe:'🟢 Safe',caution:'🟡 Caution',sunny:'Sunny ☀️',cloudy:'Partly cloudy ⛅',overcast:'Cloudy ☁️',windy:'Windy 💨',low:'Low',medium:'Moderate',high:'High',minute:' min',room:'Shower room',male:'Men’s shower',female:'Women’s shower',enter:'Confirm entry',exit:'Confirm exit',availableAt:'Estimated available time',availableNow:'Available now',myTime:'My estimated time',myTurn:'It’s your turn. Please confirm entry.',inUse:'You are using the shower.',exited:'Your shower exit is confirmed.',entryDone:'Entry confirmed. Enjoy your shower safely!',exitDone:'Exit confirmed. Thank you for using the facility!'},
  ja:{eyebrow:'BEACH SAFETY GUIDE',title:'安全な海の旅のはじまり',subtitle:'今日の海の状態を確認して、もっと軽やかに出かけましょう。',search:'海水浴場を検索',water:'水質',weather:'天気',temperature:'水温',waves:'波',facility:'BEACH FACILITY',showerTitle:'シャワー待ち状況',live:'リアルタイム',using:'利用中',waiting:'待機中',waitTime:'予想待ち時間',join:'順番待ちに登録',note:'安全情報は参考用です。現地の案内とライフガードの指示を優先してください。',reservation:'SHOWER RESERVATION',formTitle:'シャワー順番待ち',party:'利用人数',phone:'連絡先',consent:'個人情報利用に同意します。',register:'登録する',updated:'たった今更新',queue:'現在 {n} 人が待っています。',form:'{beach} のシャワー待ちに登録します。',registered:'登録が完了しました。順番が近づくとお知らせします。',safe:'🟢 安全',caution:'🟡 注意',sunny:'晴れ ☀️',cloudy:'晴れ時々曇り ⛅',overcast:'曇り ☁️',windy:'風が強い 💨',low:'低い',medium:'普通',high:'高い',minute:'分',room:'シャワー室を選択',male:'男性用シャワー',female:'女性用シャワー',enter:'入場を確認',exit:'退場を確認',availableAt:'利用可能予定時刻',availableNow:'今すぐ利用可能',myTime:'利用予定時刻',myTurn:'ご利用の順番です。入場を確認してください。',inUse:'シャワーをご利用中です。',exited:'退場を確認しました。',entryDone:'入場を確認しました。安全にご利用ください！',exitDone:'退場を確認しました。ご利用ありがとうございました！'},
  zh:{eyebrow:'BEACH SAFETY GUIDE',title:'安全海边之旅的开始',subtitle:'查看今天的海况，轻松出发。',search:'搜索海水浴场',water:'水质',weather:'天气',temperature:'水温',waves:'海浪',facility:'BEACH FACILITY',showerTitle:'淋浴排队情况',live:'实时',using:'当前使用',waiting:'排队人数',waitTime:'预计等待',join:'加入排队',note:'安全信息仅供参考，请优先遵守现场指引和救生员安排。',reservation:'SHOWER RESERVATION',formTitle:'登记淋浴排队',party:'使用人数',phone:'联系电话',consent:'我同意使用个人信息。',register:'登记',updated:'刚刚更新',queue:'目前有 {n} 人在等待。',form:'登记 {beach} 淋浴排队。',registered:'登记完成！快轮到您时会通知您。',safe:'🟢 安全',caution:'🟡 注意',sunny:'晴朗 ☀️',cloudy:'少云 ⛅',overcast:'多云 ☁️',windy:'风力较强 💨',low:'低',medium:'中等',high:'高',minute:'分钟',room:'选择淋浴间',male:'男淋浴间',female:'女淋浴间',enter:'确认入场',exit:'确认离场',availableAt:'预计可使用时间',availableNow:'现在可使用',myTime:'我的预计使用时间',myTurn:'轮到您使用淋浴间了，请确认入场。',inUse:'您正在使用淋浴间。',exited:'已确认离场。',entryDone:'已确认入场，祝您使用愉快！',exitDone:'已确认离场，感谢您的使用！'}
};
const beachLocales = {
  gwangalli:{ko:['광안리 해수욕장','부산광역시 수영구','오늘 물놀이를 추천해요! 자외선 차단제도 챙겨 주세요.'],en:['Gwangalli Beach','Suyeong-gu, Busan','A great day for swimming. Don’t forget sunscreen!'],ja:['広安里海水浴場','釜山広域市 水営区','今日は海水浴におすすめです。日焼け止めもお忘れなく。'],zh:['广安里海水浴场','釜山广域市水营区','今天推荐下水游玩，也别忘了防晒！']},
  haeundae:{ko:['해운대 해수욕장','부산광역시 해운대구','가벼운 물놀이에 좋아요. 파도에만 유의해 주세요.'],en:['Haeundae Beach','Haeundae-gu, Busan','Great for a light swim. Please watch the waves.'],ja:['海雲台海水浴場','釜山広域市 海雲台区','軽い海水浴にぴったりです。波にはご注意ください。'],zh:['海云台海水浴场','釜山广域市海云台区','适合轻松戏水，请注意海浪。']},
  songjeong:{ko:['송정 해수욕장','부산광역시 해운대구','안전요원 안내에 따라 즐겨 주세요.'],en:['Songjeong Beach','Haeundae-gu, Busan','Please enjoy the sea while following lifeguard guidance.'],ja:['松亭海水浴場','釜山広域市 海雲台区','ライフガードの案内に従ってお楽しみください。'],zh:['松亭海水浴场','釜山广域市海云台区','请遵从救生员指引，安心游玩。']},
  dadaepo:{ko:['다대포 해수욕장','부산광역시 사하구','물놀이 전 현장 통제 안내를 꼭 확인해 주세요.'],en:['Dadaepo Beach','Saha-gu, Busan','Check the on-site safety notices before entering the water.'],ja:['多大浦海水浴場','釜山広域市 沙下区','海に入る前に現地の規制案内を必ずご確認ください。'],zh:['多大浦海水浴场','釜山广域市沙下区','下水前请务必确认现场安全管制信息。']},
  songdo:{ko:['송도 해수욕장','부산광역시 서구','가족과 함께 즐기기 좋은 바다예요.'],en:['Songdo Beach','Seo-gu, Busan','A lovely beach day for the whole family.'],ja:['松島海水浴場','釜山広域市 西区','ご家族で楽しむのにぴったりな海です。'],zh:['松岛海水浴场','釜山广域市西区','很适合与家人一起享受海边时光。']}
};
beaches.forEach(b => b.queueEndsAt = Date.now() + Math.ceil(b.waiting * .75) * 60000);
let reservation = null;
let selected = beaches[0], lang = 'ko';
const $ = id => document.getElementById(id); const t = key => translations[lang][key]; const beachText = b => beachLocales[b.key][lang];
const waitMinutes = b => Math.max(0, Math.ceil((b.queueEndsAt - Date.now()) / 60000));
const clock = timestamp => new Intl.DateTimeFormat(lang === 'ko' ? 'ko-KR' : lang, {hour:'2-digit',minute:'2-digit'}).format(timestamp);
function renderList(query=''){ const list=$('beachList'); list.innerHTML=''; beaches.filter(b=>beachText(b)[0].toLowerCase().includes(query.toLowerCase())).forEach(b=>{const button=document.createElement('button');button.className='beach-chip'+(b===selected?' active':'');button.textContent='🏖 '+beachText(b)[0].replace(/ 해수욕장| Beach|海水浴場|海水浴场/g,'');button.onclick=()=>{selected=b;renderList($('beachSearch').value);renderDetail()};list.append(button)}) }
function renderDetail(){ const b=selected,[name,region,recommendation]=beachText(b),mins=waitMinutes(b); document.body.dataset.beach=b.key;$('region').textContent=region;$('beachName').textContent='🏖 '+name;$('updated').textContent=t('updated');$('score').textContent=b.score;$('face').textContent=b.icon;$('waterStatus').textContent=t(b.water);$('weatherStatus').textContent=t(b.weather);$('temperature').textContent=b.temp;$('waveStatus').textContent=t(b.waves);$('showerBeach').textContent=name+' · 🚿';$('users').textContent=b.users;$('waiting').textContent=Math.max(0,Math.ceil(mins/.75));$('minutes').textContent=mins+t('minute');$('expectedAt').textContent=mins ? t('availableAt')+' · '+clock(b.queueEndsAt) : t('availableNow');$('queueMessage').textContent=mins ? t('queue').replace('{n}',Math.max(0,Math.ceil(mins/.75))) : t('availableNow');$('formDescription').textContent=t('form').replace('{beach}',name);$('recommendationText').textContent=recommendation;$('recommendIcon').textContent=b.icon; const mine=$('myReservation'),actions=$('reservationActions'),isMine=reservation&&reservation.key===b.key;mine.hidden=!isMine;actions.hidden=!isMine;if(isMine){const room=t(reservation.gender);mine.textContent=reservation.exited?'✅ '+room+' · '+t('exited'):reservation.entered?'🚿 '+room+' · '+t('inUse'):reservation.done?'✅ '+room+' · '+t('myTurn'):'🔔 '+room+' · '+t('myTime')+' '+clock(reservation.endsAt);$('enterShower').disabled=!reservation.done||reservation.entered||reservation.exited;$('exitShower').disabled=!reservation.entered||reservation.exited} const badge=$('scoreBadge');badge.style.background=b.score<80?'#fff4d9':'#e2f8ec';badge.style.borderColor=b.score<80?'#f9d57b':'#bfead5'; }
function setLanguage(next){lang=next;document.documentElement.lang=next;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===lang));$('beachSearch').value='';renderDetail();renderList()}
function notifyReady(){if(!reservation||reservation.done||Date.now()<reservation.endsAt)return;reservation.done=true;const reservedBeach=beaches.find(b=>b.key===reservation.key);const title='🌊 바다 체크';const message=beachText(reservedBeach)[0]+' 샤워실을 이용할 차례예요.';if('Notification' in window&&Notification.permission==='granted')new Notification(title,{body:message,tag:'bada-check-queue'});const toast=$('toast');toast.textContent='🔔 '+message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),6000);renderDetail()}
document.querySelectorAll('[data-lang]').forEach(button=>button.onclick=()=>setLanguage(button.dataset.lang));$('beachSearch').oninput=e=>renderList(e.target.value.trim());$('openQueue').onclick=()=>$('queueDialog').showModal();$('closeDialog').onclick=()=>$('queueDialog').close();$('queueForm').onsubmit=async e=>{e.preventDefault();const minutes=waitMinutes(selected);reservation={key:selected.key,gender:$('showerType').value,endsAt:Date.now()+minutes*60000,done:false,entered:false,exited:false};selected.queueEndsAt+=Number($('party').value)*45000;if('Notification' in window&&Notification.permission==='default')await Notification.requestPermission();renderDetail();$('queueDialog').close();const toast=$('toast');toast.textContent=t(reservation.gender)+' · '+t('registered');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600);e.target.reset()};$('enterShower').onclick=()=>{if(!reservation.done)return;reservation.entered=true;renderDetail();const toast=$('toast');toast.textContent=t('entryDone');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)};$('exitShower').onclick=()=>{if(!reservation.entered)return;reservation.exited=true;renderDetail();const toast=$('toast');toast.textContent=t('exitDone');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)};
setLanguage('ko');renderList();
setInterval(()=>{renderDetail();notifyReady()},1000);
const partyUnits={ko:'명',en:' people',ja:'人',zh:'人'};
const showerLocations={ko:['위치','해변 입구 2번 근처'],en:['Location','Near beach entrance 2'],ja:['場所','ビーチ入口2番付近'],zh:['位置','海滩2号入口附近']};
const renderDetailBase=renderDetail;
renderDetail=()=>{renderDetailBase();const [,region]=beachText(selected);$('showerLocation').textContent='📍 '+showerLocations[lang][0]+' · '+region+' · '+showerLocations[lang][1]};
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>document.querySelectorAll('[data-party]').forEach(option=>option.textContent=option.dataset.party+partyUnits[button.dataset.lang])));
renderDetail();
const waterInfo={gwangalli:{metrics:['pH|8.1','수온|23℃','탁도|1.2 NTU','용존산소|8.4 mg/L','염분|3.3%','총인|0.02 mg/L','대장균|8 CFU/100mL'],test:'적합 · 2026.07.29',rip:'낮음',grade:'good',advice:'수질이 매우 좋습니다. 안심하고 이용하세요.'},haeundae:{metrics:['pH|7.9','수온|22℃','탁도|2.8 NTU','용존산소|7.6 mg/L','염분|3.2%','총인|0.04 mg/L','대장균|32 CFU/100mL'],test:'적합 · 2026.07.29',rip:'보통',grade:'normal',advice:'수질은 양호합니다. 파도와 현장 안내를 확인해 주세요.'},songjeong:{metrics:['pH|7.8','수온|22℃','탁도|2.4 NTU','용존산소|7.9 mg/L','염분|3.2%','총인|0.03 mg/L','대장균|21 CFU/100mL'],test:'적합 · 2026.07.28',rip:'보통',grade:'normal',advice:'수질은 양호하며, 안전요원 안내를 따라 주세요.'},dadaepo:{metrics:['pH|7.4','수온|21℃','탁도|5.9 NTU','용존산소|5.8 mg/L','염분|2.9%','총인|0.12 mg/L','대장균|164 CFU/100mL'],test:'주의 · 2026.07.29',rip:'높음',grade:'bad',advice:'이안류 위험이 있어 물놀이 전 현장 안내를 꼭 확인해 주세요.'},songdo:{metrics:['pH|8.0','수온|23℃','탁도|1.7 NTU','용존산소|8.1 mg/L','염분|3.3%','총인|0.02 mg/L','대장균|11 CFU/100mL'],test:'적합 · 2026.07.29',rip:'낮음',grade:'good',advice:'수질이 좋고 이안류 위험이 낮습니다.'}};
const openMap=()=>{const [name,region]=beachText(selected);$('mapTitle').textContent=name+' 샤워실';$('mapAddress').textContent='📍 '+region;$('mapNote').textContent='해변 입구 2번 근처에 위치해 있어요.';$('mapDialog').showModal()};
const openWater=()=>{const info=waterInfo[selected.key];$('waterTitle').textContent=beachText(selected)[0];$('waterGrade').className='water-grade '+info.grade;$('waterGrade').textContent=info.grade==='good'?'🟢 좋음':info.grade==='normal'?'🟡 보통':'🔴 주의';$('waterMetrics').innerHTML=info.metrics.map(item=>{const [label,value]=item.split('|');return '<div><span>'+label+'</span><strong>'+value+'</strong></div>'}).join('');$('testValue').textContent=info.test;$('ripValue').textContent=info.rip;$('waterAdvice').textContent=info.advice;$('waterDialog').showModal()};
$('showerLocation').addEventListener('click',openMap);$('showerLocation').style.cursor='pointer';$('waterCard').addEventListener('click',openWater);document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.closeDialog).close()));
const qualityScore={gwangalli:96,haeundae:81,songjeong:84,dadaepo:42,songdo:92};
const waterText={ko:{title:'수질 상태',test:'공식 수질 검사',rip:'이안류 위험성',good:'🟢 좋음',normal:'🟡 보통',bad:'🔴 주의',ph:'pH 농도',temp:'수온',turbidity:'탁도',oxygen:'용존산소',salinity:'염분',phosphorus:'총인',bacteria:'대장균',low:'낮음',medium:'보통',high:'높음'},en:{title:'Water quality',test:'Official water test',rip:'Rip-current risk',good:'🟢 Good',normal:'🟡 Moderate',bad:'🔴 Caution',ph:'pH',temp:'Water temperature',turbidity:'Turbidity',oxygen:'Dissolved oxygen',salinity:'Salinity',phosphorus:'Total phosphorus',bacteria:'E. coli',low:'Low',medium:'Moderate',high:'High'},ja:{title:'水質状態',test:'公式水質検査',rip:'離岸流リスク',good:'🟢 良好',normal:'🟡 普通',bad:'🔴 注意',ph:'pH濃度',temp:'水温',turbidity:'濁度',oxygen:'溶存酸素',salinity:'塩分',phosphorus:'全リン',bacteria:'大腸菌',low:'低い',medium:'普通',high:'高い'},zh:{title:'水质状态',test:'官方水质检测',rip:'离岸流风险',good:'🟢 良好',normal:'🟡 一般',bad:'🔴 注意',ph:'pH值',temp:'水温',turbidity:'浊度',oxygen:'溶解氧',salinity:'盐分',phosphorus:'总磷',bacteria:'大肠杆菌',low:'低',medium:'中等',high:'高'}};
const metricKeys=['ph','temp','turbidity','oxygen','salinity','phosphorus','bacteria'];
const waterScores=key=>{const info=waterInfo[key], labels=waterText[lang];return info.metrics.map((item,index)=>{const [,value]=item.split('|');return '<div class="metric"><span>'+labels[metricKeys[index]]+'</span><strong>'+value+'</strong></div>'}).join('')};
$('waterCard').addEventListener('click',()=>{const info=waterInfo[selected.key],score=qualityScore[selected.key],labels=waterText[lang],level=info.grade==='good'?'good':info.grade==='normal'?'normal':'bad';$('waterLabel').textContent=labels.title;$('waterGrade').textContent=labels[level];$('testLabel').textContent=labels.test;$('ripLabel').textContent=labels.rip;$('ripValue').textContent=info.rip==='낮음'?labels.low:info.rip==='보통'?labels.medium:labels.high;$('waterMetrics').innerHTML=waterScores(selected.key);$('waterGraph').innerHTML='<div class="score-scale"><div class="score-fill '+level+'" style="width:'+score+'%"></div><span class="score-point" style="left:calc('+score+'% - 22px)">'+score+'</span></div><div class="score-axis"><span>0</span><span>50</span><span>100</span></div>'});
$('showerLocation').addEventListener('click',()=>{$('mapNote').textContent=lang==='en'?'Follow the coral route from the main entrance to the shower building.':lang==='ja'?'メイン入口からサンゴ色の経路に沿ってシャワー棟へ進んでください。':lang==='zh'?'请沿珊瑚色路线从主入口前往淋浴楼。':'해변 메인 입구에서 산호색 경로를 따라 샤워실 건물로 이동하세요.';});
const extraStyle=document.createElement('style');extraStyle.textContent='.water-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:13px 0}.water-metrics .metric{background:#f5f9f8;border:1px solid #e1eeee;border-radius:10px;padding:9px}.water-metrics span{display:block;color:#647d83;font-size:.68rem}.water-metrics strong{display:block;color:#103f4b;font-size:.85rem;margin-top:3px}.score-scale{height:16px;background:linear-gradient(90deg,#ea6358 0 38%,#f2ca4e 38% 68%,#45bf82 68%);border-radius:99px;position:relative;margin-top:16px;opacity:.32}.score-fill{height:100%;border-radius:99px;background:#fff;opacity:.5}.score-point{position:absolute;top:-32px;background:#063548;color:#fff;border-radius:9px;padding:4px 7px;font-size:.75rem;font-weight:800}.score-axis{display:flex;justify-content:space-between;color:#789096;font-size:.67rem;margin:5px 0 15px}.info-dialog{border:0;border-radius:22px;box-shadow:0 24px 70px #042e3d55}.info-dialog::backdrop{background:#0635488c;backdrop-filter:blur(3px)}';document.head.append(extraStyle);
const adviceTranslations={en:{gwangalli:'Water quality is excellent. Enjoy the beach with confidence.',haeundae:'Water quality is good. Check wave conditions and local notices.',songjeong:'Water quality is good. Please follow lifeguard guidance.',dadaepo:'Rip-current risk is high. Check on-site safety notices before entering the water.',songdo:'Water quality is good and rip-current risk is low.'},ja:{gwangalli:'水質はとても良好です。安心してお楽しみください。',haeundae:'水質は良好です。波と現地案内をご確認ください。',songjeong:'水質は良好です。ライフガードの案内に従ってください。',dadaepo:'離岸流のリスクが高いため、入水前に現地の安全案内をご確認ください。',songdo:'水質は良好で、離岸流リスクは低いです。'},zh:{gwangalli:'水质非常好，您可以放心游玩。',haeundae:'水质良好，请确认海浪和现场提示。',songjeong:'水质良好，请遵从救生员指引。',dadaepo:'离岸流风险较高，下水前请确认现场安全提示。',songdo:'水质良好，离岸流风险较低。'}};
$('waterCard').addEventListener('click',()=>{if(adviceTranslations[lang])$('waterAdvice').textContent=adviceTranslations[lang][selected.key]});
$('showerLocation').addEventListener('click',()=>{$('mapDialog').querySelector('.map-preview').innerHTML='<svg viewBox="0 0 400 250" width="100%" height="100%"><defs><marker id="routeArrow" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#ff775f"/></marker></defs><rect width="400" height="250" fill="#bde8eb"/><path d="M0 0H170L205 250H0Z" fill="#e8efc8"/><path d="M22 210C85 170 78 82 158 92S238 177 331 62" fill="none" stroke="#ff775f" stroke-width="6" stroke-dasharray="2 10" marker-end="url(#routeArrow)"/><path d="M0 160L175 128" stroke="#fff" stroke-width="11"/><circle cx="22" cy="210" r="11" fill="#063548"/><text x="38" y="215" font-size="13" fill="#063548">현재 위치</text><rect x="300" y="38" width="62" height="45" rx="7" fill="#ff775f"/><text x="310" y="66" font-size="20">🚿</text><text x="294" y="101" font-size="13" fill="#063548">샤워실</text><text x="42" y="70" font-size="20">🅿️</text><text x="33" y="92" font-size="12" fill="#063548">주차장</text><text x="105" y="145" font-size="18">🚻</text><text x="94" y="164" font-size="12" fill="#063548">화장실</text><text x="245" y="202" font-size="18">🏖️</text><text x="232" y="224" font-size="12" fill="#063548">해변 산책로</text></svg><p id="mapAddress" style="position:absolute;left:12px;bottom:3px;margin:0;background:#ffffffdf;padding:7px 9px;border-radius:8px;font-size:.75rem;font-weight:700">📍 '+beachText(selected)[1]+'</p>'});
const uiMap={ko:{current:'현재 위치',shower:'샤워실',parking:'주차장',restroom:'화장실',walk:'해변 산책로',pass:'적합',fail:'부적합'},en:{current:'You are here',shower:'Shower room',parking:'Parking',restroom:'Restroom',walk:'Beach walk',pass:'Pass',fail:'Fail'},ja:{current:'現在地',shower:'シャワー室',parking:'駐車場',restroom:'トイレ',walk:'海辺の遊歩道',pass:'適合',fail:'不適合'},zh:{current:'当前位置',shower:'淋浴间',parking:'停车场',restroom:'洗手间',walk:'海滨步道',pass:'合格',fail:'不合格'}};
$('waterCard').addEventListener('click',()=>{const info=waterInfo[selected.key],words=uiMap[lang];$('testValue').textContent=(info.grade==='bad'?words.fail:words.pass)+' · '+info.test.split('·')[1].trim()});
$('showerLocation').addEventListener('click',()=>{const w=uiMap[lang];$('mapDialog').querySelector('.map-preview').innerHTML='<svg viewBox="0 0 400 250" width="100%" height="100%"><defs><marker id="routeArrow2" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#ff775f"/></marker></defs><rect width="400" height="250" fill="#bde8eb"/><path d="M0 0H170L205 250H0Z" fill="#e8efc8"/><path d="M22 210C85 170 78 82 158 92S238 177 331 62" fill="none" stroke="#ff775f" stroke-width="6" stroke-dasharray="2 10" marker-end="url(#routeArrow2)"/><path d="M0 160L175 128" stroke="#fff" stroke-width="11"/><circle cx="22" cy="210" r="11" fill="#063548"/><text x="38" y="215" font-size="13" fill="#063548">'+w.current+'</text><rect x="300" y="38" width="62" height="45" rx="7" fill="#ff775f"/><text x="310" y="66" font-size="20">🚿</text><text x="294" y="101" font-size="13" fill="#063548">'+w.shower+'</text><text x="42" y="70" font-size="20">🅿️</text><text x="33" y="92" font-size="12" fill="#063548">'+w.parking+'</text><text x="105" y="145" font-size="18">🚻</text><text x="94" y="164" font-size="12" fill="#063548">'+w.restroom+'</text><text x="245" y="202" font-size="18">🏖️</text><text x="232" y="224" font-size="12" fill="#063548">'+w.walk+'</text></svg><p id="mapAddress" style="position:absolute;left:12px;bottom:3px;margin:0;background:#ffffffdf;padding:7px 9px;border-radius:8px;font-size:.75rem;font-weight:700">📍 '+beachText(selected)[1]+'</p>'});
